site_name: Google Calendar Client
theme:
  name: material

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [components/calendar_client_api/src, components/google_calendar_client_impl/src]

nav:
  - Home: index.md
  - Components:
    - Calendar Client API: calendar_client_api.md
    - Google Calendar Client: google_calendar_client_impl.md
